// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omiiqzvfznstdwoseoag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9taWlxenZmem5zdGR3b3Nlb2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzQ2NzgsImV4cCI6MjA2MDQ1MDY3OH0.IWjgihWwonnIHMJG8B69B9gosdOdXGSIbnG15uNe_D0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);